You reached the start of the range
Oct 20, 2025, 11:41 AM
Mounting volume on: /var/lib/containers/railwayapp/bind-mounts/f073fb3a-058a-49f7-8713-a52d91b7249c/vol_yf91uzrs98k8jlbm
Mounting volume on: /var/lib/containers/railwayapp/bind-mounts/f073fb3a-058a-49f7-8713-a52d91b7249c/vol_yf91uzrs98k8jlbm
Mounting volume on: /var/lib/containers/railwayapp/bind-mounts/f073fb3a-058a-49f7-8713-a52d91b7249c/vol_yf91uzrs98k8jlbm
Mounting volume on: /var/lib/containers/railwayapp/bind-mounts/f073fb3a-058a-49f7-8713-a52d91b7249c/vol_yf91uzrs98k8jlbm
Starting Container
PostgreSQL Database directory appears to contain a database; Skipping initialization
Certificate will not expire
2025-10-20 09:44:36.415 UTC [6] LOG:  starting PostgreSQL 17.6 (Debian 17.6-2.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
2025-10-20 09:44:36.415 UTC [6] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-10-20 09:44:36.415 UTC [6] LOG:  listening on IPv6 address "::", port 5432
2025-10-20 09:44:36.419 UTC [6] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-10-20 09:44:36.432 UTC [29] LOG:  database system was interrupted; last known up at 2025-10-17 15:44:40 UTC
2025-10-20 09:44:36.856 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
2025-10-20 09:44:36.865 UTC [29] LOG:  redo starts at 0/1D46658
2025-10-20 09:44:36.865 UTC [29] LOG:  invalid record length at 0/1D46760: expected at least 24, got 0
2025-10-20 09:44:36.865 UTC [29] LOG:  redo done at 0/1D46728 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-10-20 09:44:36.875 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
2025-10-20 09:44:36.907 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.006 s, total=0.037 s; sync files=2, longest=0.004 s, average=0.003 s; distance=0 kB, estimate=0 kB; lsn=0/1D46760, redo lsn=0/1D46760
2025-10-20 09:44:36.916 UTC [6] LOG:  database system is ready to accept connections
2025-10-20 09:44:48.097 UTC [35] ERROR:  relation "categories" does not exist at character 43
2025-10-20 09:44:48.097 UTC [35] STATEMENT:  select "id", "name", "display_order" from "categories" order by "categories"."display_order", "categories"."name"
2025-10-20 09:44:48.103 UTC [34] ERROR:  column tags.category_id does not exist at character 45
2025-10-20 09:44:48.103 UTC [34] STATEMENT:  select distinct "tags"."id", "tags"."name", "tags"."category_id" from "tags" inner join "video_tags" on "tags"."id" = "video_tags"."tag_id" order by "tags"."name"
2025-10-20 09:44:48.135 UTC [36] ERROR:  column "category_id" does not exist at character 22
2025-10-20 09:44:48.135 UTC [36] STATEMENT:  select "id", "name", "category_id" from "tags" where "tags"."id" in ($1, $2, $3) order by "tags"."name"
2025-10-20 09:44:48.179 UTC [33] ERROR:  column tags.category_id does not exist at character 45
2025-10-20 09:44:48.179 UTC [33] STATEMENT:  select distinct "tags"."id", "tags"."name", "tags"."category_id" from "tags" inner join "video_tags" on "tags"."id" = "video_tags"."tag_id" order by "tags"."name"